### ISSUE TITLE
Using libpeas as plugin system for python applications

### ISSUE THREAD

**Issue by tobimensch** [gregier/libpeas#4]
Hello,

I understand that so far libpeas is being used to provide script language plugins for compiled languages. (ie. to allw for python plugins for the C application gedit)

libpeas also uses gobject/gir, so would it be possible to use libpeas from a pure python application
to extend it with python/lua/another-script-language/or-even-C-compiled plugins?

If this is possible, I really would like to see an example for that usage. If it's not possible yet but could be made possible, then this is a feature request.

Greetings

**Comment by gregier** [comment]
More than likely this is not possible due to toggle refs and lack of working bindings for GObject.Parameter. Although, LGI does not use toggle refs.

See: [https://mail.gnome.org/archives/desktop-devel-list/2010-August/msg00036.html](https://mail.gnome.org/archives/desktop-devel-list/2010-August/msg00036.html)


Please do not open issues or pull requests here as this is a personal repository.
